---
  - name: Install the Hashicorp Suite
    hosts: "{{ which_hosts }}"
    become: yes
    roles:
      - role: hashicorp-tools
    post_tasks:
      - name: Add Hashi Tools to Path for Users
        lineinfile:
          dest: '{{ item }}.bash_profile'
          line: 'PATH=$PATH:/opt/bin'
          insertbefore: 'export PATH'
        with_items:
          - '/root/'
          - '/home/ansible/'
        ignore_errors: yes
