---
  - name: Install the Hashicorp Suite
    hosts: all
    become: yes
    roles:
      - role: hashicorp-tools
        hashicorp_tools:
          packer:
            state: latest
          terraform:
            state: latest
          nomad:
            state: latest
          consul:
            state: absent
          vault:
            state: latest
    post_tasks:
      - name: Add Hashi Tools to Path for Users
        lineinfile:
          dest: '{{ item }}.bash_profile'
          line: 'PATH=$PATH:/opt/bin'
          insertbefore: 'export PATH'
        with_items:
          - '/root/'
          - '/home/ansible/'
        ignore_errors: yes
